#!/usr/bin/php
<?php
$doc = <<<DOC
Generate diff

Usage:
  gendiff (-h | --help)
  gendiff (-v | --version)

Options:
  -h --help     Show this screen.
  -v --version  Show version.

DOC;

require(__DIR__ . '/src/docopt.php');
$args = Docopt::handle($doc, array('version'=>'Gendiff 0.1.0'));
foreach ($args as $k=>$v)
    echo $k.': '.json_encode($v).PHP_EOL;